spring.application.name=acervo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.ulkqahrdudsdzuolipwk&password=eDWfN8UJ7Wi2zucv

spring.jpa.show-sql=true